<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMnrkpxm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnrkpxm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMnrkpxm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMnrkpxm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMnrkpxm\appProdProjectContainer([
    'container.build_hash' => 'Mnrkpxm',
    'container.build_id' => '6fa5ddcf',
    'container.build_time' => 1633003961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnrkpxm');
